const todoActionTypes = {
  SET_TODO_FROM_FIREBASE: "SET_TODO_FROM_FIREBASE",
  ADD_TODO_START: "ADD_TODO_START",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  REMOVE_TODO_START: "REMOVE_TODO_START",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  SET_TODO_ON_TIMTER: "SET_TODO_ON_TIMTER",
  CLEAR_TODO_LIST: "CLEAR_TODO_LIST",
  SET_ANOTHER_TODO_START: "SET_ANOTHER_TODO_START",
  SET_ANOTHER_TODO_SUCCESS: "SET_ANOTHER_TODO_SUCCESS",
  GET_WEEKLY_TODO_START: "GET_WEEKLY_TODO_START",
  GET_WEEKLY_TODO_SUCCESS: "GET_WEEKLY_TODO_SUCCESS",
  OPEN_TIMER: "OPEN_TIMER",
  CLOSE_TIMER: "CLOSE_TIMER",
  STOPPED_WORKING: "STOPPED_WORKING",
  STARTED_WORKING: "STARTED_WORKING",
  STORE_UPDATED_TODO_START: "STORE_UPDATED_TODO_START",
  STORE_UPDATED_TODO_FINISH: "STORE_UPDATED_TODO_FINISH"
};

export default todoActionTypes;
