const todoActionTypes = {
  SET_TODO_FROM_FIREBASE: "SET_TODO_FROM_FIREBASE",
  ADD_TODO_START: "ADD_TODO_START",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  REMOVE_TODO_START: "REMOVE_TODO_START",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  CLEAR_TODO_LIST: "CLEAR_TODO_LIST",
  FILTER_TODO_FOR_THIS_MONTH: "FILTER_TODO_FOR_THIS_MONTH"
};

export default todoActionTypes;
