const asyncActionTypes = {
  ASYNC_ACTION_START: "ASYNC_ACTION_START",
  ASYNC_ACTION_FINISH: "ASYNC_ACTION_FINISH",
  ASYNC_ACTION_ERROR: "ASYNC_ACTION_ERROR",
  INCREASE_TODO_FORM_STEP: "INCREASE_TODO_FORM_STEP",
  DECREASE_TODO_FORM_STEP: "DECREASE_TODO_FORM_STEP",
  SET_TODO_FORM_STEP_TO_ZERO: "SET_TODO_FORM_STEP_TO_ZERO",
  TOGGLE_TODO_FORM_OPEN: "TOGGLE_TODO_FORM_OPEN"
};

export default asyncActionTypes;
